version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0.3

workflows:
  publish-orb:
    jobs:
      - orb-tools/lint
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: appoptics/appoptics@dev:${CIRCLE_BRANCH}
      #     validate: true
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: appoptics/appoptics
      #     validate: true
      #     filters:
      #       branches:
      #         only: master
